apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/gbrivate/ninja-belt-ng:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/gbrivate/ninja-belt-ng:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: ninja-belt-ng
        chartPath: charts/ninja-belt-ng
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/gbrivate/ninja-belt-ng"
          image.tag: "{{.DIGEST_HEX}}"
